{"name":"Local: exception","url":"c:\\Users\\DCL\\Desktop\\Phitron\\Batch 4\\Python\\exception.py","tests":[{"id":1714935872585,"input":"","output":""}],"interactive":false,"memoryLimit":1024,"timeLimit":3000,"srcPath":"c:\\Users\\DCL\\Desktop\\Phitron\\Batch 4\\Python\\exception.py","group":"local","local":true}